import type { TestCaseDefinition } from "./types";

export const TEST_CASES_100: TestCaseDefinition[] = [
  {
    "testCaseNumber": 1,
    "caseId": "TG-TEST-0001",
    "documentId": "DOC-TEST-0001",
    "processingRunId": "RUN-TEST-0001-cb21ee69",
    "category": "A_VALID_DOCUMENT",
    "categoryCode": "A",
    "title": "Valid Document Inspection (Case #1)",
    "description": "Authentic credential with valid MRZ, clean ELA, and verified citizen identity",
    "expectedDecision": "PASS",
    "expectedRiskLevel": "LOW",
    "inputSource": "TEST_DATA",
    "inputHash": "59473ae6517a5f37c0d3fa0f41ca0012b57b7018c24761d32448578cfa78929b",
    "qualityScore": 95,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 5,
    "faceDetected": true,
    "faceMatchScore": 95,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 2,
    "caseId": "TG-TEST-0002",
    "documentId": "DOC-TEST-0002",
    "processingRunId": "RUN-TEST-0002-ab5210e1",
    "category": "A_VALID_DOCUMENT",
    "categoryCode": "A",
    "title": "Valid Document Inspection (Case #2)",
    "description": "Authentic credential with valid MRZ, clean ELA, and verified citizen identity",
    "expectedDecision": "PASS",
    "expectedRiskLevel": "LOW",
    "inputSource": "TEST_DATA",
    "inputHash": "b1bafb50250799503c470f64db400a724fe133487bff3e370b6067eed2272c9f",
    "qualityScore": 95,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 5,
    "faceDetected": true,
    "faceMatchScore": 95,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 3,
    "caseId": "TG-TEST-0003",
    "documentId": "DOC-TEST-0003",
    "processingRunId": "RUN-TEST-0003-0c04222b",
    "category": "A_VALID_DOCUMENT",
    "categoryCode": "A",
    "title": "Valid Document Inspection (Case #3)",
    "description": "Authentic credential with valid MRZ, clean ELA, and verified citizen identity",
    "expectedDecision": "PASS",
    "expectedRiskLevel": "LOW",
    "inputSource": "TEST_DATA",
    "inputHash": "1714c89747a1822384288dbe55e3757a50aad3aa62b0d9bb73402d7c74d663de",
    "qualityScore": 95,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 5,
    "faceDetected": true,
    "faceMatchScore": 95,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 4,
    "caseId": "TG-TEST-0004",
    "documentId": "DOC-TEST-0004",
    "processingRunId": "RUN-TEST-0004-8b8ecef2",
    "category": "A_VALID_DOCUMENT",
    "categoryCode": "A",
    "title": "Valid Document Inspection (Case #4)",
    "description": "Authentic credential with valid MRZ, clean ELA, and verified citizen identity",
    "expectedDecision": "PASS",
    "expectedRiskLevel": "LOW",
    "inputSource": "TEST_DATA",
    "inputHash": "6a2d76d7005cc07e984ad33b1c1c9631e79907db5a083b6d21ce243a9fc84911",
    "qualityScore": 95,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 5,
    "faceDetected": true,
    "faceMatchScore": 95,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 5,
    "caseId": "TG-TEST-0005",
    "documentId": "DOC-TEST-0005",
    "processingRunId": "RUN-TEST-0005-d879ae3e",
    "category": "A_VALID_DOCUMENT",
    "categoryCode": "A",
    "title": "Valid Document Inspection (Case #5)",
    "description": "Authentic credential with valid MRZ, clean ELA, and verified citizen identity",
    "expectedDecision": "PASS",
    "expectedRiskLevel": "LOW",
    "inputSource": "TEST_DATA",
    "inputHash": "5c729255e332947764502c459f8f70c5398c42ae45f55744a7bd2635f030e9fe",
    "qualityScore": 95,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 5,
    "faceDetected": true,
    "faceMatchScore": 95,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 6,
    "caseId": "TG-TEST-0006",
    "documentId": "DOC-TEST-0006",
    "processingRunId": "RUN-TEST-0006-428e306a",
    "category": "B_OCR_FAILURE",
    "categoryCode": "B",
    "title": "Low Contrast OCR Failure (Case #6)",
    "description": "Faint ink print resulting in unreadable VIZ fields requiring secondary review",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "e2aa1eca053f568c14492cafcf7bc0d3b2b3bec65f30b67375f172159892addc",
    "qualityScore": 65,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 7,
    "caseId": "TG-TEST-0007",
    "documentId": "DOC-TEST-0007",
    "processingRunId": "RUN-TEST-0007-e91bac3d",
    "category": "B_OCR_FAILURE",
    "categoryCode": "B",
    "title": "Low Contrast OCR Failure (Case #7)",
    "description": "Faint ink print resulting in unreadable VIZ fields requiring secondary review",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "dab81958e9cca7b9b2a274c1e844779a70e63df239deb4ca4ecffccd752aa521",
    "qualityScore": 65,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 8,
    "caseId": "TG-TEST-0008",
    "documentId": "DOC-TEST-0008",
    "processingRunId": "RUN-TEST-0008-206452e3",
    "category": "B_OCR_FAILURE",
    "categoryCode": "B",
    "title": "Low Contrast OCR Failure (Case #8)",
    "description": "Faint ink print resulting in unreadable VIZ fields requiring secondary review",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "eebd8a795c19c9eebb27d0be2ccbacb5aa2a6e646e040b579860d2245e6f7ec4",
    "qualityScore": 65,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 9,
    "caseId": "TG-TEST-0009",
    "documentId": "DOC-TEST-0009",
    "processingRunId": "RUN-TEST-0009-eeac1c60",
    "category": "C_LOW_IMAGE_QUALITY",
    "categoryCode": "C",
    "title": "Sub-Standard Resolution (Case #9)",
    "description": "Image resolution below 72 DPI threshold requiring recapture",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "971520ae076495e6e02ed4415777ecad788b688acfbea92aedd5025bd5d192fc",
    "qualityScore": 35,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 0,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 10,
    "caseId": "TG-TEST-0010",
    "documentId": "DOC-TEST-0010",
    "processingRunId": "RUN-TEST-0010-823b287d",
    "category": "C_LOW_IMAGE_QUALITY",
    "categoryCode": "C",
    "title": "Sub-Standard Resolution (Case #10)",
    "description": "Image resolution below 72 DPI threshold requiring recapture",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "46021a7461223d0df3bfe0bde04ab6be772cb014bc84e0a3746a190a1bb3fab5",
    "qualityScore": 35,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 0,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 11,
    "caseId": "TG-TEST-0011",
    "documentId": "DOC-TEST-0011",
    "processingRunId": "RUN-TEST-0011-e7538382",
    "category": "C_LOW_IMAGE_QUALITY",
    "categoryCode": "C",
    "title": "Sub-Standard Resolution (Case #11)",
    "description": "Image resolution below 72 DPI threshold requiring recapture",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "657f404acecc14f1f102c830fe6ad68498da10755fafe58a802c83279d70def6",
    "qualityScore": 35,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 0,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 12,
    "caseId": "TG-TEST-0012",
    "documentId": "DOC-TEST-0012",
    "processingRunId": "RUN-TEST-0012-685a7b92",
    "category": "D_BLUR",
    "categoryCode": "D",
    "title": "Motion Blur Artifacts (Case #12)",
    "description": "Laplacian variance below 60.0 indicative of camera movement during capture",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "180813b736be4ccd5283e544c2e937c120cd2731b6614aa2c184e4e6ff07779f",
    "qualityScore": 40,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 0,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 13,
    "caseId": "TG-TEST-0013",
    "documentId": "DOC-TEST-0013",
    "processingRunId": "RUN-TEST-0013-b8d811e4",
    "category": "D_BLUR",
    "categoryCode": "D",
    "title": "Motion Blur Artifacts (Case #13)",
    "description": "Laplacian variance below 60.0 indicative of camera movement during capture",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "9e37bc93a40989c01f1b512ff80f6d332c62541c55ac44a3b90b4531a53388e7",
    "qualityScore": 40,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 0,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 14,
    "caseId": "TG-TEST-0014",
    "documentId": "DOC-TEST-0014",
    "processingRunId": "RUN-TEST-0014-32c962a0",
    "category": "D_BLUR",
    "categoryCode": "D",
    "title": "Motion Blur Artifacts (Case #14)",
    "description": "Laplacian variance below 60.0 indicative of camera movement during capture",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "bd3cd3b3b5d00e47e9bb390711137112b6279a2bd38eadd880c61e1e702c3312",
    "qualityScore": 40,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 0,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 15,
    "caseId": "TG-TEST-0015",
    "documentId": "DOC-TEST-0015",
    "processingRunId": "RUN-TEST-0015-558dc6bd",
    "category": "E_GLARE",
    "categoryCode": "E",
    "title": "Laminate Specular Glare (Case #15)",
    "description": "Excessive light reflection obscuring critical photo and MRZ zones",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "353d49c40de6616a08312784f6545361e4cc6a36712d3f0921c7d010bbe1c275",
    "qualityScore": 45,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 20,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 16,
    "caseId": "TG-TEST-0016",
    "documentId": "DOC-TEST-0016",
    "processingRunId": "RUN-TEST-0016-4e2aa160",
    "category": "E_GLARE",
    "categoryCode": "E",
    "title": "Laminate Specular Glare (Case #16)",
    "description": "Excessive light reflection obscuring critical photo and MRZ zones",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "c6d75921b67aadd991670dafd4709b4212ddcc4f810088d58ce9c28601e6bd75",
    "qualityScore": 45,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 20,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 17,
    "caseId": "TG-TEST-0017",
    "documentId": "DOC-TEST-0017",
    "processingRunId": "RUN-TEST-0017-eaa5bb8e",
    "category": "E_GLARE",
    "categoryCode": "E",
    "title": "Laminate Specular Glare (Case #17)",
    "description": "Excessive light reflection obscuring critical photo and MRZ zones",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "bdf2bb526264ea0b4bd3df3b6123bd13b80a633171ae089d6a941d9081af557d",
    "qualityScore": 45,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 20,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 18,
    "caseId": "TG-TEST-0018",
    "documentId": "DOC-TEST-0018",
    "processingRunId": "RUN-TEST-0018-a5c296ef",
    "category": "F_PERSPECTIVE_DISTORTION",
    "categoryCode": "F",
    "title": "Extreme Keystone Skew (Case #18)",
    "description": "Severe quadrilateral skew exceeding perspective rectification bounds",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "ff9c12f643200fb3d481f96182e6475a9dda24cd77f65c3f6b852cbda0bf753c",
    "qualityScore": 55,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 15,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 19,
    "caseId": "TG-TEST-0019",
    "documentId": "DOC-TEST-0019",
    "processingRunId": "RUN-TEST-0019-9d99c5aa",
    "category": "F_PERSPECTIVE_DISTORTION",
    "categoryCode": "F",
    "title": "Extreme Keystone Skew (Case #19)",
    "description": "Severe quadrilateral skew exceeding perspective rectification bounds",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "0774900251a52d7b26df49973773cf991e7463698b9e92a96feaef29e2f14196",
    "qualityScore": 55,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 15,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 20,
    "caseId": "TG-TEST-0020",
    "documentId": "DOC-TEST-0020",
    "processingRunId": "RUN-TEST-0020-33c934e6",
    "category": "F_PERSPECTIVE_DISTORTION",
    "categoryCode": "F",
    "title": "Extreme Keystone Skew (Case #20)",
    "description": "Severe quadrilateral skew exceeding perspective rectification bounds",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "34e9b208fab36dea4fd27c933b49b633337bef7f41a1819ce4f3ccbe3ee25384",
    "qualityScore": 55,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 15,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 21,
    "caseId": "TG-TEST-0021",
    "documentId": "DOC-TEST-0021",
    "processingRunId": "RUN-TEST-0021-171b3788",
    "category": "G_PARTIAL_DOCUMENT",
    "categoryCode": "G",
    "title": "Partial Document Crop (Case #21)",
    "description": "Missing outer border coordinates and partial MRZ cutoff",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "d596fac0fa239587f836463c75a0d54a5838ff9b7aa0e057da4513aeadbfb439",
    "qualityScore": 50,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 25,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 22,
    "caseId": "TG-TEST-0022",
    "documentId": "DOC-TEST-0022",
    "processingRunId": "RUN-TEST-0022-10a5468a",
    "category": "G_PARTIAL_DOCUMENT",
    "categoryCode": "G",
    "title": "Partial Document Crop (Case #22)",
    "description": "Missing outer border coordinates and partial MRZ cutoff",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "967814e0859ee60e9673d27dfeccbe35a5e033321de7db4462f26db55237011b",
    "qualityScore": 50,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 25,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 23,
    "caseId": "TG-TEST-0023",
    "documentId": "DOC-TEST-0023",
    "processingRunId": "RUN-TEST-0023-9ca28dee",
    "category": "H_INVALID_MRZ",
    "categoryCode": "H",
    "title": "Non-Standard MRZ Characters (Case #23)",
    "description": "Invalid punctuation and symbols detected in ICAO lines",
    "expectedDecision": "FAIL",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "f8172b9e4b992bb628e6772a5cff001ac6f50e5bd32d7c0aa5a3034fe6d3cf81",
    "qualityScore": 85,
    "ocrSuccess": true,
    "mrzValid": false,
    "tamperScore": 45,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 24,
    "caseId": "TG-TEST-0024",
    "documentId": "DOC-TEST-0024",
    "processingRunId": "RUN-TEST-0024-48dcb6d6",
    "category": "H_INVALID_MRZ",
    "categoryCode": "H",
    "title": "Non-Standard MRZ Characters (Case #24)",
    "description": "Invalid punctuation and symbols detected in ICAO lines",
    "expectedDecision": "FAIL",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "115b26e5db8fa38d0f4f44c69fcbecc79aea7b74e9b84da3e11c12ed464922d4",
    "qualityScore": 85,
    "ocrSuccess": true,
    "mrzValid": false,
    "tamperScore": 45,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 25,
    "caseId": "TG-TEST-0025",
    "documentId": "DOC-TEST-0025",
    "processingRunId": "RUN-TEST-0025-3c45353a",
    "category": "H_INVALID_MRZ",
    "categoryCode": "H",
    "title": "Non-Standard MRZ Characters (Case #25)",
    "description": "Invalid punctuation and symbols detected in ICAO lines",
    "expectedDecision": "FAIL",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "af738be7aa386a6e46b16fcd6597215aa647c5becd99da44bdb075cea3b96191",
    "qualityScore": 85,
    "ocrSuccess": true,
    "mrzValid": false,
    "tamperScore": 45,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 26,
    "caseId": "TG-TEST-0026",
    "documentId": "DOC-TEST-0026",
    "processingRunId": "RUN-TEST-0026-e474a915",
    "category": "I_MRZ_CHECKSUM_FAILURE",
    "categoryCode": "I",
    "title": "ICAO 7-3-1 Checksum Mismatch (Case #26)",
    "description": "Document number check digit does not match mathematical computation",
    "expectedDecision": "FAIL",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "55e2d974058ffb8ef184af8586694505c18225053505326169425b5bef5fb610",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": false,
    "tamperScore": 70,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 27,
    "caseId": "TG-TEST-0027",
    "documentId": "DOC-TEST-0027",
    "processingRunId": "RUN-TEST-0027-a299a92e",
    "category": "I_MRZ_CHECKSUM_FAILURE",
    "categoryCode": "I",
    "title": "ICAO 7-3-1 Checksum Mismatch (Case #27)",
    "description": "Document number check digit does not match mathematical computation",
    "expectedDecision": "FAIL",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "1bb374512d5de0af3c1b4cbcbdca2ccd492bf0dbbcd4b258b6eb1328761af582",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": false,
    "tamperScore": 70,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 28,
    "caseId": "TG-TEST-0028",
    "documentId": "DOC-TEST-0028",
    "processingRunId": "RUN-TEST-0028-aba9df3e",
    "category": "I_MRZ_CHECKSUM_FAILURE",
    "categoryCode": "I",
    "title": "ICAO 7-3-1 Checksum Mismatch (Case #28)",
    "description": "Document number check digit does not match mathematical computation",
    "expectedDecision": "FAIL",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "292ce0d8e1c5069de5252aaae19bd0c719524d1db016510c64c972003a665117",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": false,
    "tamperScore": 70,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 29,
    "caseId": "TG-TEST-0029",
    "documentId": "DOC-TEST-0029",
    "processingRunId": "RUN-TEST-0029-434dd790",
    "category": "J_CROSS_FIELD_INCONSISTENCY",
    "categoryCode": "J",
    "title": "VIZ vs MRZ Name Mismatch (Case #29)",
    "description": "Given name in visual zone differs from parsed MRZ identity string",
    "expectedDecision": "FAIL",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "cfd4ca5a881d96592215ca687b181c32dc631afc75357333d8ba9224782c2f78",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 65,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "CONFLICT",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 30,
    "caseId": "TG-TEST-0030",
    "documentId": "DOC-TEST-0030",
    "processingRunId": "RUN-TEST-0030-f4844d37",
    "category": "J_CROSS_FIELD_INCONSISTENCY",
    "categoryCode": "J",
    "title": "VIZ vs MRZ Name Mismatch (Case #30)",
    "description": "Given name in visual zone differs from parsed MRZ identity string",
    "expectedDecision": "FAIL",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "eaaf04d651439bb35ba7bc4265721db4e5f6f89d26e1c8e84c633dcbfcd14fd2",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 65,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "CONFLICT",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 31,
    "caseId": "TG-TEST-0031",
    "documentId": "DOC-TEST-0031",
    "processingRunId": "RUN-TEST-0031-eb8fe4d2",
    "category": "J_CROSS_FIELD_INCONSISTENCY",
    "categoryCode": "J",
    "title": "VIZ vs MRZ Name Mismatch (Case #31)",
    "description": "Given name in visual zone differs from parsed MRZ identity string",
    "expectedDecision": "FAIL",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "4eaf90de852ecacab3426c6a2dba548c205c10f6f8ba0d49861cea3fac3d5a67",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 65,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "CONFLICT",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 32,
    "caseId": "TG-TEST-0032",
    "documentId": "DOC-TEST-0032",
    "processingRunId": "RUN-TEST-0032-d9eaf02d",
    "category": "K_EXPIRED_DOCUMENT",
    "categoryCode": "K",
    "title": "Expired Travel Credential (Case #32)",
    "description": "Document expiration date precedes current border gateway UTC clock",
    "expectedDecision": "FAIL",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "6bc70e18968a4f8bbdaa764d03f93dec1ba66cf9e4208f069276fc70e392f30c",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": 90,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 33,
    "caseId": "TG-TEST-0033",
    "documentId": "DOC-TEST-0033",
    "processingRunId": "RUN-TEST-0033-55fab505",
    "category": "K_EXPIRED_DOCUMENT",
    "categoryCode": "K",
    "title": "Expired Travel Credential (Case #33)",
    "description": "Document expiration date precedes current border gateway UTC clock",
    "expectedDecision": "FAIL",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "79efab5dc145f6544da0bd79ad797535bc417a4ccc3661053579ac7161f3b530",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": 90,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 34,
    "caseId": "TG-TEST-0034",
    "documentId": "DOC-TEST-0034",
    "processingRunId": "RUN-TEST-0034-8cc04c06",
    "category": "K_EXPIRED_DOCUMENT",
    "categoryCode": "K",
    "title": "Expired Travel Credential (Case #34)",
    "description": "Document expiration date precedes current border gateway UTC clock",
    "expectedDecision": "FAIL",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "5e7480e5a8e4663f2c8abad6c94a5546d61f78a46a122b1bc5aadbb0a9022873",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": 90,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 35,
    "caseId": "TG-TEST-0035",
    "documentId": "DOC-TEST-0035",
    "processingRunId": "RUN-TEST-0035-fd75d1fd",
    "category": "L_MISSING_FIELDS",
    "categoryCode": "L",
    "title": "Missing Mandatory Fields (Case #35)",
    "description": "Required nationality or date of birth omitted from credential",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "96b430b69de7bc07705857a465a208cf1bfb699f29e45d0a5378012d65fd0b17",
    "qualityScore": 80,
    "ocrSuccess": true,
    "mrzValid": false,
    "tamperScore": 30,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 36,
    "caseId": "TG-TEST-0036",
    "documentId": "DOC-TEST-0036",
    "processingRunId": "RUN-TEST-0036-e0e932f1",
    "category": "L_MISSING_FIELDS",
    "categoryCode": "L",
    "title": "Missing Mandatory Fields (Case #36)",
    "description": "Required nationality or date of birth omitted from credential",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "c94ca75cb60f91a16ee401e9e8594f52c9aac8b193b9495cf8efa03dddf39402",
    "qualityScore": 80,
    "ocrSuccess": true,
    "mrzValid": false,
    "tamperScore": 30,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 37,
    "caseId": "TG-TEST-0037",
    "documentId": "DOC-TEST-0037",
    "processingRunId": "RUN-TEST-0037-fc5ac822",
    "category": "L_MISSING_FIELDS",
    "categoryCode": "L",
    "title": "Missing Mandatory Fields (Case #37)",
    "description": "Required nationality or date of birth omitted from credential",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "79eeb80368b8345b1d9a6a019a2ef0b9090f8e54fc907937ce3fa033270910a3",
    "qualityScore": 80,
    "ocrSuccess": true,
    "mrzValid": false,
    "tamperScore": 30,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 38,
    "caseId": "TG-TEST-0038",
    "documentId": "DOC-TEST-0038",
    "processingRunId": "RUN-TEST-0038-e4542bcb",
    "category": "M_TAMPERING_INDICATORS",
    "categoryCode": "M",
    "title": "Digital Photo Splicing (ELA) (Case #38)",
    "description": "High Error Level Analysis variance in portrait bounding box",
    "expectedDecision": "FAIL",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "45e32aeffa89a54593251281863c37bedb88a5ba04deae658494a86c77ed4e56",
    "qualityScore": 85,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 88,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "CONFLICT",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 39,
    "caseId": "TG-TEST-0039",
    "documentId": "DOC-TEST-0039",
    "processingRunId": "RUN-TEST-0039-d42d11f3",
    "category": "M_TAMPERING_INDICATORS",
    "categoryCode": "M",
    "title": "Digital Photo Splicing (ELA) (Case #39)",
    "description": "High Error Level Analysis variance in portrait bounding box",
    "expectedDecision": "FAIL",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "9f2c22088fe28ca4c49323303d5484c0055ba956d8c4cee7a30f01371ffa1fd6",
    "qualityScore": 85,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 88,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "CONFLICT",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 40,
    "caseId": "TG-TEST-0040",
    "documentId": "DOC-TEST-0040",
    "processingRunId": "RUN-TEST-0040-632c9db3",
    "category": "M_TAMPERING_INDICATORS",
    "categoryCode": "M",
    "title": "Digital Photo Splicing (ELA) (Case #40)",
    "description": "High Error Level Analysis variance in portrait bounding box",
    "expectedDecision": "FAIL",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "81d250ed516a2e4398e2552151a451e79d0e9732e155319e3960ec2398973e73",
    "qualityScore": 85,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 88,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "CONFLICT",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 41,
    "caseId": "TG-TEST-0041",
    "documentId": "DOC-TEST-0041",
    "processingRunId": "RUN-TEST-0041-06d3f91c",
    "category": "M_TAMPERING_INDICATORS",
    "categoryCode": "M",
    "title": "Digital Photo Splicing (ELA) (Case #41)",
    "description": "High Error Level Analysis variance in portrait bounding box",
    "expectedDecision": "FAIL",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "521276e079c5fc100c8b28e167e5175dba07fdff2a7910865063913e09c2f9b6",
    "qualityScore": 85,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 88,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "CONFLICT",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 42,
    "caseId": "TG-TEST-0042",
    "documentId": "DOC-TEST-0042",
    "processingRunId": "RUN-TEST-0042-a7d182d8",
    "category": "N_FACE_NOT_DETECTED",
    "categoryCode": "N",
    "title": "No Portrait Detected (Case #42)",
    "description": "Face detector found 0 candidate regions in credential photo zone",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "8109a44a1ff63d56ed1d04b3ae04a94f519915a041bc303beba1deb413fb87ee",
    "qualityScore": 85,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 40,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 43,
    "caseId": "TG-TEST-0043",
    "documentId": "DOC-TEST-0043",
    "processingRunId": "RUN-TEST-0043-a03a54b2",
    "category": "N_FACE_NOT_DETECTED",
    "categoryCode": "N",
    "title": "No Portrait Detected (Case #43)",
    "description": "Face detector found 0 candidate regions in credential photo zone",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "c550b8423e0fc608155a48c908025ac188e0de7bae8ac3e4e114230677ef32f9",
    "qualityScore": 85,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 40,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 44,
    "caseId": "TG-TEST-0044",
    "documentId": "DOC-TEST-0044",
    "processingRunId": "RUN-TEST-0044-83d30f41",
    "category": "N_FACE_NOT_DETECTED",
    "categoryCode": "N",
    "title": "No Portrait Detected (Case #44)",
    "description": "Face detector found 0 candidate regions in credential photo zone",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "68d7d1446a147a5b01317629e891076d17a3c570ec999e80874d8f0374e2f1e1",
    "qualityScore": 85,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 40,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 45,
    "caseId": "TG-TEST-0045",
    "documentId": "DOC-TEST-0045",
    "processingRunId": "RUN-TEST-0045-c7b085b0",
    "category": "O_FACE_QUALITY_INSUFFICIENT",
    "categoryCode": "O",
    "title": "Insufficient Facial Quality (Case #45)",
    "description": "Portrait over-compressed; skin chrominance locus check fails",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "4e839ec7809f38d422f073494f388a7ea61d7481ba8635d931dcb49f96c88360",
    "qualityScore": 75,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 20,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 46,
    "caseId": "TG-TEST-0046",
    "documentId": "DOC-TEST-0046",
    "processingRunId": "RUN-TEST-0046-b01a62ea",
    "category": "O_FACE_QUALITY_INSUFFICIENT",
    "categoryCode": "O",
    "title": "Insufficient Facial Quality (Case #46)",
    "description": "Portrait over-compressed; skin chrominance locus check fails",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "e1ee8d409722850ca6b6ca9a30e3c350f2b9106ee4fc97c529fb2d28cb2c4d57",
    "qualityScore": 75,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 20,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 47,
    "caseId": "TG-TEST-0047",
    "documentId": "DOC-TEST-0047",
    "processingRunId": "RUN-TEST-0047-13b28bd6",
    "category": "O_FACE_QUALITY_INSUFFICIENT",
    "categoryCode": "O",
    "title": "Insufficient Facial Quality (Case #47)",
    "description": "Portrait over-compressed; skin chrominance locus check fails",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "8dfd66a5945beaa513d20e5d3b363ffce6400b9498016692c66659b1bd6460a7",
    "qualityScore": 75,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 20,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 48,
    "caseId": "TG-TEST-0048",
    "documentId": "DOC-TEST-0048",
    "processingRunId": "RUN-TEST-0048-1c94c0bc",
    "category": "P_IDENTITY_REF_UNAVAILABLE",
    "categoryCode": "P",
    "title": "Database Face Ref Unavailable (Case #48)",
    "description": "No authoritative photo registered; matchScore returned as null / NOT_AVAILABLE",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "12755b5f63786760c1410952f4b4d3dd9057de22a07a340477105791c464f605",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 49,
    "caseId": "TG-TEST-0049",
    "documentId": "DOC-TEST-0049",
    "processingRunId": "RUN-TEST-0049-df199de7",
    "category": "P_IDENTITY_REF_UNAVAILABLE",
    "categoryCode": "P",
    "title": "Database Face Ref Unavailable (Case #49)",
    "description": "No authoritative photo registered; matchScore returned as null / NOT_AVAILABLE",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "7e6886728808a379ddce9786c758ee646605fc158bc35762ed7b93a734804b09",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 50,
    "caseId": "TG-TEST-0050",
    "documentId": "DOC-TEST-0050",
    "processingRunId": "RUN-TEST-0050-e622a72d",
    "category": "P_IDENTITY_REF_UNAVAILABLE",
    "categoryCode": "P",
    "title": "Database Face Ref Unavailable (Case #50)",
    "description": "No authoritative photo registered; matchScore returned as null / NOT_AVAILABLE",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "3987a20158bc6561d42a3dd5ec472955e8ea22ca07ceff8a33b044414c62f352",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 51,
    "caseId": "TG-TEST-0051",
    "documentId": "DOC-TEST-0051",
    "processingRunId": "RUN-TEST-0051-d2a491d4",
    "category": "Q_DATABASE_RECORD_FOUND",
    "categoryCode": "Q",
    "title": "Authoritative Database Verified (Case #51)",
    "description": "Document number matches citizen registry; 1:1 facial biometric confirmed",
    "expectedDecision": "PASS",
    "expectedRiskLevel": "LOW",
    "inputSource": "TEST_DATA",
    "inputHash": "ba81f3ad1783c8a8b090c75a90ad11ba375f5de5c9e4d911f858009f9f94a013",
    "qualityScore": 95,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 5,
    "faceDetected": true,
    "faceMatchScore": 96,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 52,
    "caseId": "TG-TEST-0052",
    "documentId": "DOC-TEST-0052",
    "processingRunId": "RUN-TEST-0052-6bbed5fc",
    "category": "Q_DATABASE_RECORD_FOUND",
    "categoryCode": "Q",
    "title": "Authoritative Database Verified (Case #52)",
    "description": "Document number matches citizen registry; 1:1 facial biometric confirmed",
    "expectedDecision": "PASS",
    "expectedRiskLevel": "LOW",
    "inputSource": "TEST_DATA",
    "inputHash": "affe1e94fb3223c63f3c1f163ba2c50dd80a4d7dcd8a3ed1473b25be89048b2b",
    "qualityScore": 95,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 5,
    "faceDetected": true,
    "faceMatchScore": 96,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 53,
    "caseId": "TG-TEST-0053",
    "documentId": "DOC-TEST-0053",
    "processingRunId": "RUN-TEST-0053-40c252ae",
    "category": "Q_DATABASE_RECORD_FOUND",
    "categoryCode": "Q",
    "title": "Authoritative Database Verified (Case #53)",
    "description": "Document number matches citizen registry; 1:1 facial biometric confirmed",
    "expectedDecision": "PASS",
    "expectedRiskLevel": "LOW",
    "inputSource": "TEST_DATA",
    "inputHash": "7392c47b479c90edf8609a67f0356dac97090e1b4f4b743fcf32d86f06c90cac",
    "qualityScore": 95,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 5,
    "faceDetected": true,
    "faceMatchScore": 96,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 54,
    "caseId": "TG-TEST-0054",
    "documentId": "DOC-TEST-0054",
    "processingRunId": "RUN-TEST-0054-0bfac0ec",
    "category": "Q_DATABASE_RECORD_FOUND",
    "categoryCode": "Q",
    "title": "Authoritative Database Verified (Case #54)",
    "description": "Document number matches citizen registry; 1:1 facial biometric confirmed",
    "expectedDecision": "PASS",
    "expectedRiskLevel": "LOW",
    "inputSource": "TEST_DATA",
    "inputHash": "7ae5f3a4832b6de71d640d8e55a2131ddab832925027c5ca752043aff16f3a64",
    "qualityScore": 95,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 5,
    "faceDetected": true,
    "faceMatchScore": 96,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 55,
    "caseId": "TG-TEST-0055",
    "documentId": "DOC-TEST-0055",
    "processingRunId": "RUN-TEST-0055-440b064e",
    "category": "R_DATABASE_RECORD_NOT_FOUND",
    "categoryCode": "R",
    "title": "Unregistered Traveler (No Record) (Case #55)",
    "description": "No record found in national registry; does not constitute automatic fraud",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "21622e2d24a363e29d0642c3cd9ae5f9c34b940f87df3d29d07c9813f3c97644",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 56,
    "caseId": "TG-TEST-0056",
    "documentId": "DOC-TEST-0056",
    "processingRunId": "RUN-TEST-0056-1c7813c6",
    "category": "R_DATABASE_RECORD_NOT_FOUND",
    "categoryCode": "R",
    "title": "Unregistered Traveler (No Record) (Case #56)",
    "description": "No record found in national registry; does not constitute automatic fraud",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "1181eddefd1cde4cc1571e53777c26b6f012beb2ec7e36a2fddceeb2c65ef486",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 57,
    "caseId": "TG-TEST-0057",
    "documentId": "DOC-TEST-0057",
    "processingRunId": "RUN-TEST-0057-a4aeaf49",
    "category": "R_DATABASE_RECORD_NOT_FOUND",
    "categoryCode": "R",
    "title": "Unregistered Traveler (No Record) (Case #57)",
    "description": "No record found in national registry; does not constitute automatic fraud",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "ef45584a45aae051be03363ed213ba8f30e7bfb4955bb09d7285d2eeb1c1b5e7",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 58,
    "caseId": "TG-TEST-0058",
    "documentId": "DOC-TEST-0058",
    "processingRunId": "RUN-TEST-0058-d7a325b1",
    "category": "R_DATABASE_RECORD_NOT_FOUND",
    "categoryCode": "R",
    "title": "Unregistered Traveler (No Record) (Case #58)",
    "description": "No record found in national registry; does not constitute automatic fraud",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "ab4d24e45ad5f880942a2815b807cd3b0eed97bae20fe828752467565960a6a8",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 59,
    "caseId": "TG-TEST-0059",
    "documentId": "DOC-TEST-0059",
    "processingRunId": "RUN-TEST-0059-bbf3c15f",
    "category": "S_DATABASE_UNAVAILABLE",
    "categoryCode": "S",
    "title": "Database Network Outage (Case #59)",
    "description": "External identity registry unreachable; system operates in air-gapped standby",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "27c48519d3b7e7b532096db0e08598c73451fcf677bb695c45d36f09764949f3",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "UNAVAILABLE",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 60,
    "caseId": "TG-TEST-0060",
    "documentId": "DOC-TEST-0060",
    "processingRunId": "RUN-TEST-0060-a9c64935",
    "category": "S_DATABASE_UNAVAILABLE",
    "categoryCode": "S",
    "title": "Database Network Outage (Case #60)",
    "description": "External identity registry unreachable; system operates in air-gapped standby",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "71ec9ddfe435a0aa375857d84e3779988ba4dcc7c760e9afd2c203010f2d3e60",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "UNAVAILABLE",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 61,
    "caseId": "TG-TEST-0061",
    "documentId": "DOC-TEST-0061",
    "processingRunId": "RUN-TEST-0061-a38176f3",
    "category": "S_DATABASE_UNAVAILABLE",
    "categoryCode": "S",
    "title": "Database Network Outage (Case #61)",
    "description": "External identity registry unreachable; system operates in air-gapped standby",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "c718f6bbd75f49c8f81fee7733930119e1134c8ee5925278960e6e427a454244",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "UNAVAILABLE",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 62,
    "caseId": "TG-TEST-0062",
    "documentId": "DOC-TEST-0062",
    "processingRunId": "RUN-TEST-0062-ab379f36",
    "category": "T_MULTIPLE_DATABASE_MATCHES",
    "categoryCode": "T",
    "title": "Ambiguous Multiple Matches (Case #62)",
    "description": "Query returned multiple identity records requiring manual disambiguation",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "f1e65e5e27237a9379a52716cbe29a4fda30b2981af7c5e6aed380e18ae493fb",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "MULTIPLE",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 63,
    "caseId": "TG-TEST-0063",
    "documentId": "DOC-TEST-0063",
    "processingRunId": "RUN-TEST-0063-294610c6",
    "category": "T_MULTIPLE_DATABASE_MATCHES",
    "categoryCode": "T",
    "title": "Ambiguous Multiple Matches (Case #63)",
    "description": "Query returned multiple identity records requiring manual disambiguation",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "ad2a8fae273abaea68d515af84069c72d88a117525ff3339c59ef833e15126d8",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "MULTIPLE",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 64,
    "caseId": "TG-TEST-0064",
    "documentId": "DOC-TEST-0064",
    "processingRunId": "RUN-TEST-0064-07834d3b",
    "category": "U_CONFLICTING_DATABASE_INFO",
    "categoryCode": "U",
    "title": "Conflicting Registry Information (Case #64)",
    "description": "Database registered DOB conflicts with physical credential DOB",
    "expectedDecision": "FAIL",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "18c7e05a8d5ded3bae29fa05c1b742f89c9298783161f8a905b34fc748c4e2f1",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 20,
    "faceDetected": true,
    "faceMatchScore": 92,
    "databaseStatus": "CONFLICT",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 65,
    "caseId": "TG-TEST-0065",
    "documentId": "DOC-TEST-0065",
    "processingRunId": "RUN-TEST-0065-a5bcbe14",
    "category": "U_CONFLICTING_DATABASE_INFO",
    "categoryCode": "U",
    "title": "Conflicting Registry Information (Case #65)",
    "description": "Database registered DOB conflicts with physical credential DOB",
    "expectedDecision": "FAIL",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "e4427a776afe38829b09fe9e0e11d3525db845e858edea6610607f6ea70ff8bc",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 20,
    "faceDetected": true,
    "faceMatchScore": 92,
    "databaseStatus": "CONFLICT",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 66,
    "caseId": "TG-TEST-0066",
    "documentId": "DOC-TEST-0066",
    "processingRunId": "RUN-TEST-0066-0bed0954",
    "category": "V_AI_UNAVAILABLE",
    "categoryCode": "V",
    "title": "Python LLM Engine Offline (Case #66)",
    "description": "Local port 8000 unreachable; client-side rules run in degraded mode",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "5d3e55d3bb1d6085f2e8113a334baccd766862a7ec84b00ae0775a5b2d3b7b1c",
    "qualityScore": 85,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 67,
    "caseId": "TG-TEST-0067",
    "documentId": "DOC-TEST-0067",
    "processingRunId": "RUN-TEST-0067-5fb58ac3",
    "category": "V_AI_UNAVAILABLE",
    "categoryCode": "V",
    "title": "Python LLM Engine Offline (Case #67)",
    "description": "Local port 8000 unreachable; client-side rules run in degraded mode",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "0f01eb14e328099ca13e81146fb75152762ca705f415e775bce56469e5a78ac5",
    "qualityScore": 85,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 68,
    "caseId": "TG-TEST-0068",
    "documentId": "DOC-TEST-0068",
    "processingRunId": "RUN-TEST-0068-9e54538a",
    "category": "V_AI_UNAVAILABLE",
    "categoryCode": "V",
    "title": "Python LLM Engine Offline (Case #68)",
    "description": "Local port 8000 unreachable; client-side rules run in degraded mode",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "6becc346ef35a7358521985f451ee8d2010edd39eaae48a7adc6d2c6a92f8ad6",
    "qualityScore": 85,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 69,
    "caseId": "TG-TEST-0069",
    "documentId": "DOC-TEST-0069",
    "processingRunId": "RUN-TEST-0069-0fa3b317",
    "category": "W_LLM_UNAVAILABLE",
    "categoryCode": "W",
    "title": "Deep Reasoning Timeout (Case #69)",
    "description": "Optical archetype comparison timed out; fallback to local heuristic",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "38bca70e2ef8161da6ceb32927c113423a20b3d5a6942af7acb9ef010ec60712",
    "qualityScore": 85,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 70,
    "caseId": "TG-TEST-0070",
    "documentId": "DOC-TEST-0070",
    "processingRunId": "RUN-TEST-0070-ee5d1b29",
    "category": "W_LLM_UNAVAILABLE",
    "categoryCode": "W",
    "title": "Deep Reasoning Timeout (Case #70)",
    "description": "Optical archetype comparison timed out; fallback to local heuristic",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "7f29cc78c3e1052e02772fa06e7db8377523937bc9ff98f96b9acbcb68137594",
    "qualityScore": 85,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 71,
    "caseId": "TG-TEST-0071",
    "documentId": "DOC-TEST-0071",
    "processingRunId": "RUN-TEST-0071-9e1c801a",
    "category": "X_PROCESSING_TIMEOUT",
    "categoryCode": "X",
    "title": "15-Second Ingestion Timeout (Case #71)",
    "description": "Network latency exceeded threshold; operation aborted safely",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "359460b1fe1a182e991d8f9fc2da644d7bff95800c4ac01c1d3d188cf15e153f",
    "qualityScore": 70,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 0,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "UNAVAILABLE",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 72,
    "caseId": "TG-TEST-0072",
    "documentId": "DOC-TEST-0072",
    "processingRunId": "RUN-TEST-0072-ac6d453c",
    "category": "X_PROCESSING_TIMEOUT",
    "categoryCode": "X",
    "title": "15-Second Ingestion Timeout (Case #72)",
    "description": "Network latency exceeded threshold; operation aborted safely",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "4bf84f178121c61b8f311ea305c4a8f88cd82394c2a0f184bb3798cd88fb596e",
    "qualityScore": 70,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 0,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "UNAVAILABLE",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 73,
    "caseId": "TG-TEST-0073",
    "documentId": "DOC-TEST-0073",
    "processingRunId": "RUN-TEST-0073-840b0bf5",
    "category": "X_PROCESSING_TIMEOUT",
    "categoryCode": "X",
    "title": "15-Second Ingestion Timeout (Case #73)",
    "description": "Network latency exceeded threshold; operation aborted safely",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "e12ea2c82fb85acdbd8a8e809a24ff092d9d115934b517b7e23e69fbe4e644ea",
    "qualityScore": 70,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 0,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "UNAVAILABLE",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 74,
    "caseId": "TG-TEST-0074",
    "documentId": "DOC-TEST-0074",
    "processingRunId": "RUN-TEST-0074-f1edd1db",
    "category": "Y_MALFORMED_API_RESPONSE",
    "categoryCode": "Y",
    "title": "Corrupted API Payload (Case #74)",
    "description": "JSON parse error caught by boundary; zero fabricated fallback",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "acc122a92d3887393a7cbb3d20d3f51246b1b1036661f57008f5909e67706aeb",
    "qualityScore": 80,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 0,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "UNAVAILABLE",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 75,
    "caseId": "TG-TEST-0075",
    "documentId": "DOC-TEST-0075",
    "processingRunId": "RUN-TEST-0075-e36a9545",
    "category": "Y_MALFORMED_API_RESPONSE",
    "categoryCode": "Y",
    "title": "Corrupted API Payload (Case #75)",
    "description": "JSON parse error caught by boundary; zero fabricated fallback",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "50d51c2959da8f48462ccc54e979d30c342af24fae98a2e96530a5ffddbcaa26",
    "qualityScore": 80,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 0,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "UNAVAILABLE",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 76,
    "caseId": "TG-TEST-0076",
    "documentId": "DOC-TEST-0076",
    "processingRunId": "RUN-TEST-0076-9e80177f",
    "category": "Z_DUPLICATE_SUBMISSION",
    "categoryCode": "Z",
    "title": "Identical Hash Resubmission (Case #76)",
    "description": "Duplicate file submitted; verified that new processingRunId is generated",
    "expectedDecision": "PASS",
    "expectedRiskLevel": "LOW",
    "inputSource": "TEST_DATA",
    "inputHash": "405f431328d085676f6665908785d92b49ee0f33f5c00b2de101205f80de413b",
    "qualityScore": 95,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 5,
    "faceDetected": true,
    "faceMatchScore": 95,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 77,
    "caseId": "TG-TEST-0077",
    "documentId": "DOC-TEST-0077",
    "processingRunId": "RUN-TEST-0077-ac61b550",
    "category": "Z_DUPLICATE_SUBMISSION",
    "categoryCode": "Z",
    "title": "Identical Hash Resubmission (Case #77)",
    "description": "Duplicate file submitted; verified that new processingRunId is generated",
    "expectedDecision": "PASS",
    "expectedRiskLevel": "LOW",
    "inputSource": "TEST_DATA",
    "inputHash": "24f69fa1780442766083d6e7c717d15f085a58b46d5ecece1aa7595f8d407ece",
    "qualityScore": 95,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 5,
    "faceDetected": true,
    "faceMatchScore": 95,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 78,
    "caseId": "TG-TEST-0078",
    "documentId": "DOC-TEST-0078",
    "processingRunId": "RUN-TEST-0078-adc444b2",
    "category": "AA_CONCURRENT_SUBMISSIONS",
    "categoryCode": "AA",
    "title": "Concurrent Multi-Case Ingestion (Case #78)",
    "description": "Parallel processing of independent cases; zero cross-contamination",
    "expectedDecision": "PASS",
    "expectedRiskLevel": "LOW",
    "inputSource": "TEST_DATA",
    "inputHash": "fe782a8c03226d2ae374a41f00e8e242d1fd807691a8805b92541e77d4b4f4d7",
    "qualityScore": 92,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 8,
    "faceDetected": true,
    "faceMatchScore": 94,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 79,
    "caseId": "TG-TEST-0079",
    "documentId": "DOC-TEST-0079",
    "processingRunId": "RUN-TEST-0079-d52929ce",
    "category": "AA_CONCURRENT_SUBMISSIONS",
    "categoryCode": "AA",
    "title": "Concurrent Multi-Case Ingestion (Case #79)",
    "description": "Parallel processing of independent cases; zero cross-contamination",
    "expectedDecision": "PASS",
    "expectedRiskLevel": "LOW",
    "inputSource": "TEST_DATA",
    "inputHash": "4d09c96a5a7d69008f1f216336d3e39522d0edb80c2d2990615af0b34df3ca44",
    "qualityScore": 92,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 8,
    "faceDetected": true,
    "faceMatchScore": 94,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 80,
    "caseId": "TG-TEST-0080",
    "documentId": "DOC-TEST-0080",
    "processingRunId": "RUN-TEST-0080-7c4e4f48",
    "category": "AA_CONCURRENT_SUBMISSIONS",
    "categoryCode": "AA",
    "title": "Concurrent Multi-Case Ingestion (Case #80)",
    "description": "Parallel processing of independent cases; zero cross-contamination",
    "expectedDecision": "PASS",
    "expectedRiskLevel": "LOW",
    "inputSource": "TEST_DATA",
    "inputHash": "4a0eae84f12b91cebed9c84dba86089068416b423485c989aa5421a79df72079",
    "qualityScore": 92,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 8,
    "faceDetected": true,
    "faceMatchScore": 94,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 81,
    "caseId": "TG-TEST-0081",
    "documentId": "DOC-TEST-0081",
    "processingRunId": "RUN-TEST-0081-d1654be2",
    "category": "AB_STALE_RESULT_SCENARIO",
    "categoryCode": "AB",
    "title": "Active Run Token Race Guard (Case #81)",
    "description": "Document A followed immediately by Document B; Document A results discarded",
    "expectedDecision": "PASS",
    "expectedRiskLevel": "LOW",
    "inputSource": "TEST_DATA",
    "inputHash": "d19bdcbb4282c7b1b8d0bf5051411753e218e8391fea9a126262d2e06e60aa28",
    "qualityScore": 95,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 5,
    "faceDetected": true,
    "faceMatchScore": 95,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 82,
    "caseId": "TG-TEST-0082",
    "documentId": "DOC-TEST-0082",
    "processingRunId": "RUN-TEST-0082-04c00c0d",
    "category": "AB_STALE_RESULT_SCENARIO",
    "categoryCode": "AB",
    "title": "Active Run Token Race Guard (Case #82)",
    "description": "Document A followed immediately by Document B; Document A results discarded",
    "expectedDecision": "PASS",
    "expectedRiskLevel": "LOW",
    "inputSource": "TEST_DATA",
    "inputHash": "dac6bc2e534f07e700f88cbaafe40a2130de3f832d72945695dbe2a8ad1a55ac",
    "qualityScore": 95,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 5,
    "faceDetected": true,
    "faceMatchScore": 95,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 83,
    "caseId": "TG-TEST-0083",
    "documentId": "DOC-TEST-0083",
    "processingRunId": "RUN-TEST-0083-c0cf2f16",
    "category": "AB_STALE_RESULT_SCENARIO",
    "categoryCode": "AB",
    "title": "Active Run Token Race Guard (Case #83)",
    "description": "Document A followed immediately by Document B; Document A results discarded",
    "expectedDecision": "PASS",
    "expectedRiskLevel": "LOW",
    "inputSource": "TEST_DATA",
    "inputHash": "c57dfec4e2d8c243e38802307e10d0dcaf0574566bde37f7c1225eadbc29980d",
    "qualityScore": 95,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 5,
    "faceDetected": true,
    "faceMatchScore": 95,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 84,
    "caseId": "TG-TEST-0084",
    "documentId": "DOC-TEST-0084",
    "processingRunId": "RUN-TEST-0084-49db5354",
    "category": "AC_REFRESH_DURING_PROCESSING",
    "categoryCode": "AC",
    "title": "Client Refresh During Pipeline (Case #84)",
    "description": "Simulated browser reload; state resets cleanly without orphaned results",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "b2e646fdcebedc887f550a84911b261146e60e43abedf637aaba41e3266d4036",
    "qualityScore": 80,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 0,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 85,
    "caseId": "TG-TEST-0085",
    "documentId": "DOC-TEST-0085",
    "processingRunId": "RUN-TEST-0085-cfc12bf4",
    "category": "AC_REFRESH_DURING_PROCESSING",
    "categoryCode": "AC",
    "title": "Client Refresh During Pipeline (Case #85)",
    "description": "Simulated browser reload; state resets cleanly without orphaned results",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "612281b4536046fedce403a4ca74f95ceaf50405dea866f1218541b1416663ef",
    "qualityScore": 80,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 0,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 86,
    "caseId": "TG-TEST-0086",
    "documentId": "DOC-TEST-0086",
    "processingRunId": "RUN-TEST-0086-de6ddb93",
    "category": "AD_NETWORK_INTERRUPTION",
    "categoryCode": "AD",
    "title": "Network Disconnect Mid-Upload (Case #86)",
    "description": "BaaS disconnect; case saved to IndexedDB with pending_sync status",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "7736e9d28cc66e144fa20a3cd7ed65fb19fcca4ac37d73502cc0e482ae024f24",
    "qualityScore": 85,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "UNAVAILABLE",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 87,
    "caseId": "TG-TEST-0087",
    "documentId": "DOC-TEST-0087",
    "processingRunId": "RUN-TEST-0087-f219e0f0",
    "category": "AD_NETWORK_INTERRUPTION",
    "categoryCode": "AD",
    "title": "Network Disconnect Mid-Upload (Case #87)",
    "description": "BaaS disconnect; case saved to IndexedDB with pending_sync status",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "a6ae029a537a42f55f4439b51293cfb816a640c5a94e8389fa6cc21ad5aeff01",
    "qualityScore": 85,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "UNAVAILABLE",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 88,
    "caseId": "TG-TEST-0088",
    "documentId": "DOC-TEST-0088",
    "processingRunId": "RUN-TEST-0088-00db397f",
    "category": "AE_REALTIME_RECONNECT",
    "categoryCode": "AE",
    "title": "WebSocket Pub/Sub Reconnection (Case #88)",
    "description": "Socket dropped and re-established; events deduplicated via Set<eventId>",
    "expectedDecision": "PASS",
    "expectedRiskLevel": "LOW",
    "inputSource": "TEST_DATA",
    "inputHash": "78be6b1f44f4c57c3dd1546d70b5765e68176bda4bece053b8a95f6eb8e82a7d",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 5,
    "faceDetected": true,
    "faceMatchScore": 95,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 89,
    "caseId": "TG-TEST-0089",
    "documentId": "DOC-TEST-0089",
    "processingRunId": "RUN-TEST-0089-645a322d",
    "category": "AE_REALTIME_RECONNECT",
    "categoryCode": "AE",
    "title": "WebSocket Pub/Sub Reconnection (Case #89)",
    "description": "Socket dropped and re-established; events deduplicated via Set<eventId>",
    "expectedDecision": "PASS",
    "expectedRiskLevel": "LOW",
    "inputSource": "TEST_DATA",
    "inputHash": "ad93d3c2fce358f52e10a36eeec5bde5c08148dae3fdf1332bff62e3295d76b8",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 5,
    "faceDetected": true,
    "faceMatchScore": 95,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 90,
    "caseId": "TG-TEST-0090",
    "documentId": "DOC-TEST-0090",
    "processingRunId": "RUN-TEST-0090-60814c69",
    "category": "AF_REPORT_GENERATION_FAILURE",
    "categoryCode": "AF",
    "title": "Report Generation Failover (Case #90)",
    "description": "PDF rendering quota failure trapped gracefully with officer notification",
    "expectedDecision": "PASS",
    "expectedRiskLevel": "LOW",
    "inputSource": "TEST_DATA",
    "inputHash": "c5bc209f7f20c58a1e8e5bbfaa6e9ad98d8de84b907775fc2b3310b63b596c45",
    "qualityScore": 92,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 5,
    "faceDetected": true,
    "faceMatchScore": 95,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 91,
    "caseId": "TG-TEST-0091",
    "documentId": "DOC-TEST-0091",
    "processingRunId": "RUN-TEST-0091-d418cfa2",
    "category": "AF_REPORT_GENERATION_FAILURE",
    "categoryCode": "AF",
    "title": "Report Generation Failover (Case #91)",
    "description": "PDF rendering quota failure trapped gracefully with officer notification",
    "expectedDecision": "PASS",
    "expectedRiskLevel": "LOW",
    "inputSource": "TEST_DATA",
    "inputHash": "df37daae4385c6384e0440f6120437c740dbb2fbea01107ba45319110a92c341",
    "qualityScore": 92,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 5,
    "faceDetected": true,
    "faceMatchScore": 95,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 92,
    "caseId": "TG-TEST-0092",
    "documentId": "DOC-TEST-0092",
    "processingRunId": "RUN-TEST-0092-3d27cc18",
    "category": "AG_AUTHORIZATION_FAILURE",
    "categoryCode": "AG",
    "title": "Privilege Escalation Attempt (Case #92)",
    "description": "Officer role attempting supervisor case risk override; blocked by RBAC",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "45894de314ffe6dea64f212833e7d64d6667753929fcb4e2e2bb9a5d6a2a1f42",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 93,
    "caseId": "TG-TEST-0093",
    "documentId": "DOC-TEST-0093",
    "processingRunId": "RUN-TEST-0093-9d45fc5d",
    "category": "AG_AUTHORIZATION_FAILURE",
    "categoryCode": "AG",
    "title": "Privilege Escalation Attempt (Case #93)",
    "description": "Officer role attempting supervisor case risk override; blocked by RBAC",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "0fb49a224d1811ae4d6b87cd632f7c5566288b7020882b45e03ee777f626ba8f",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 94,
    "caseId": "TG-TEST-0094",
    "documentId": "DOC-TEST-0094",
    "processingRunId": "RUN-TEST-0094-29af2bc3",
    "category": "AG_AUTHORIZATION_FAILURE",
    "categoryCode": "AG",
    "title": "Privilege Escalation Attempt (Case #94)",
    "description": "Officer role attempting supervisor case risk override; blocked by RBAC",
    "expectedDecision": "REVIEW",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "8fd53b3cdff6e152f165ffbe653a210ba21058d28c06876487236ba222d114ac",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 95,
    "caseId": "TG-TEST-0095",
    "documentId": "DOC-TEST-0095",
    "processingRunId": "RUN-TEST-0095-8e9fb8ee",
    "category": "AH_UNAUTHORIZED_CASE_ACCESS",
    "categoryCode": "AH",
    "title": "IDOR Cross-User Access Attempt (Case #95)",
    "description": "User A attempting to query User B case; blocked by PostgreSQL RLS",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "932ae19b6972d6f463e7941197cd3db29a2a1c25822946f92554e57102648472",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 96,
    "caseId": "TG-TEST-0096",
    "documentId": "DOC-TEST-0096",
    "processingRunId": "RUN-TEST-0096-4f0a4714",
    "category": "AH_UNAUTHORIZED_CASE_ACCESS",
    "categoryCode": "AH",
    "title": "IDOR Cross-User Access Attempt (Case #96)",
    "description": "User A attempting to query User B case; blocked by PostgreSQL RLS",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "c667b659d8a3df734c63b2ccf6e2b2d8838fc18d362c1455bdc49b4d20320137",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 97,
    "caseId": "TG-TEST-0097",
    "documentId": "DOC-TEST-0097",
    "processingRunId": "RUN-TEST-0097-23308426",
    "category": "AH_UNAUTHORIZED_CASE_ACCESS",
    "categoryCode": "AH",
    "title": "IDOR Cross-User Access Attempt (Case #97)",
    "description": "User A attempting to query User B case; blocked by PostgreSQL RLS",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "5e3414334c647f4a1865f3c95bb65234ada649340d011a03caa99483a92a85ad",
    "qualityScore": 90,
    "ocrSuccess": true,
    "mrzValid": true,
    "tamperScore": 10,
    "faceDetected": true,
    "faceMatchScore": null,
    "databaseStatus": "FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 98,
    "caseId": "TG-TEST-0098",
    "documentId": "DOC-TEST-0098",
    "processingRunId": "RUN-TEST-0098-d5f35f44",
    "category": "AI_INVALID_DOCUMENT_FORMAT",
    "categoryCode": "AI",
    "title": "Malicious File Type Injection (Case #98)",
    "description": "SVG with script payload or executable renamed as .jpg; rejected by magic bytes",
    "expectedDecision": "FAIL",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "1e49315ccf86880b121d4cbd5c0ceb227deab38042a3192169fc33eaf130f7f9",
    "qualityScore": 0,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 100,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 99,
    "caseId": "TG-TEST-0099",
    "documentId": "DOC-TEST-0099",
    "processingRunId": "RUN-TEST-0099-15d96840",
    "category": "AI_INVALID_DOCUMENT_FORMAT",
    "categoryCode": "AI",
    "title": "Malicious File Type Injection (Case #99)",
    "description": "SVG with script payload or executable renamed as .jpg; rejected by magic bytes",
    "expectedDecision": "FAIL",
    "expectedRiskLevel": "HIGH",
    "inputSource": "TEST_DATA",
    "inputHash": "bdfe8100298b5a8a6d663249ff7cef1a81685f4d3a680d4327e00010475ed0df",
    "qualityScore": 0,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 100,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  },
  {
    "testCaseNumber": 100,
    "caseId": "TG-TEST-0100",
    "documentId": "DOC-TEST-0100",
    "processingRunId": "RUN-TEST-0100-6eb780ff",
    "category": "AJ_OVERSIZED_UPLOAD",
    "categoryCode": "AJ",
    "title": "28MB Oversized Payload (Case #100)",
    "description": "File exceeding 25MB boundary rejected at gateway before memory consumption",
    "expectedDecision": "INCONCLUSIVE",
    "expectedRiskLevel": "MEDIUM",
    "inputSource": "TEST_DATA",
    "inputHash": "8ca718e5957011ab1ed234217e9869604a867a88e72546083b679383b472e625",
    "qualityScore": 0,
    "ocrSuccess": false,
    "mrzValid": false,
    "tamperScore": 0,
    "faceDetected": false,
    "faceMatchScore": null,
    "databaseStatus": "NOT_FOUND",
    "environment": "TEST",
    "notProduction": true
  }
];
